### ISSUE TITLE
error when installed from nuget

### ISSUE THREAD

**Issue by radicalgeek** [baseclass/Contrib.SpecFlow.Selenium.NUnit#1]
With a clean MVC 4 project in VS 2012, I add a new class library project, and then add nuget packages. I add specflow, webdriver, web driver support and this baseclass. as soon as I add a new feature file I get this error:
# error Generation error: Unable to find plugin in the plugin search path: Baseclass.Contrib.SpecFlow.Selenium.NUnit. Please check http://go.specflow.org/doc-plugins for details.

I notice that the app.config plugins path refers to 1.0 not 1.1. however, this same issue ixists in the example project but that builds fine. What gives???

**Comment by romerod** [comment]
Hi Mark,

thanks for the contacting me, I will look into it. First impression: does the new project use the same version of SpecFlow as the example project?

I'll get back to you, as soon as I know more.

May I ask you if you plan to use this in a large scale project?

Kind regards

Daniel

---

Von: Mark Jones [notifications@github.com]
Gesendet: Montag, 16. September 2013 15:48
An: baseclass/Contrib.SpecFlow.Selenium.NUnit
Betreff: [Contrib.SpecFlow.Selenium.NUnit] error when installed from nuget (#1)

With a clean MVC 4 project in VS 2012, I add a new class library project, and then add nuget packages. I add specflow, webdriver, web driver support and this baseclass. as soon as I add a new feature file I get this error:

#error Generation error: Unable to find plugin in the plugin search path: Baseclass.Contrib.SpecFlow.Selenium.NUnit. Please check http://go.specflow.org/doc-plugins for details.

I notice that the app.config plugins path refers to 1.0 not 1.1. however, this same issue ixists in the example project but that builds fine. What gives???

**Comment by radicalgeek** [comment]
It is the dependencies. If you install the baseclass first, before you install specFlow and webdriver it works fine. I notice it depends on an old version of webdriver now. 

Do you have more documentation? I am having issues with the chrome binary path now, can i set it some how with the params in the config file? 

as for the scale, I don't know yet, I am just trying to prove the concept at the mo. I will certainly use it on my personal stuff, but if I can get it working well and I can convince the QA team, who knows!

Thanks for a really good lib though btw! I was trying to do this for a few days before I found yours, well done.

**Comment by radicalgeek** [comment]
I get the same error if I try to add the specflow dynamic assist package.

**Comment by romerod** [comment]
Nuget packages is updated to use newest version of Selenium and AutoFac
