### ISSUE TITLE
Intergration with TFS build. 

### ISSUE THREAD

**Issue by radicalgeek** [baseclass/Contrib.SpecFlow.Selenium.NUnit#2]
I am having some trouble with this project / autofac when trying to run from TFS build (2010) using nunit. I have tried a number of path options, but I see continue to see the same behaviour. the relevent error in the build log is: 

ProcessModel: Default    DomainUsage: Multiple Execution Runtime: net-3.5 .F.F.F.F.F.F.F.F Tests run: 8, Errors: 0, Failures: 8, Inconclusive: 0, Time: 0.4253568 seconds   Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0  Errors and Failures: 1) SetUp Error : RegistrationForm.Tests.Acceptance.Features.UserRegistrationFeature    SetUp : System.Configuration.ConfigurationErrorsException : The type 'OpenQA.Selenium.Remote.RemoteWebDriver, Baseclass.Contrib.SpecFlow.Selenium.NUnit.SpecFlowPlugin' could not be found. It may require assembly qualification, e.g. "MyType, MyAssembly".    at Autofac.Configuration.ConfigurationRegistrar.LoadType(String typeName, Assembly defaultAssembly)    at Autofac.Configuration.ConfigurationRegistrar.RegisterConfiguredComponents(ContainerBuilder builder, SectionHandler configurationSection)    at Autofac.Configuration.ConfigurationRegistrar.RegisterConfigurationSection(ContainerBuilder builder, SectionHandler configurationSection)    at Autofac.Configuration.Core.ConfigurationModule.Load(ContainerBuilder builder)    at Autofac.Module.Configure(IComponentRegistry componentRegistry)    at Autofac.ContainerBuilder.Build(IComponentRegistry componentRegistry, Boolean excludeDefaultModules)    at Autofac.ContainerBuilder.Build(ContainerBuildOptions options)    at RegistrationForm.Tests.Acceptance.Features.UserRegistrationFeature.FeatureSetup() in c:\Builds\1\Testing\RegistrationForm - Nightly - Main\Sources\Testing\RegistrationForm\Main\RegistrationForm.Tests.Acceptance\Features\UserRegistration.feature.cs:line 0  2) Parent Failure : RegistrationForm.Tests.Acceptance.Features.UserRegistrationFeature.UserSignsUpWithDifferingPasswords on Firefox    TestFixtureSetUp failed in UserRegistrationFeature 3) Parent Failure : RegistrationForm.Tests.Acceptance.Features.UserRegistrationFeature.UserSignsUpWithDifferingPasswords on Safari    TestFixtureSetUp failed in UserRegistrationFeature 4) Parent Failure : RegistrationForm.Tests.Acceptance.Features.UserRegistrationFeature.UserSignsUpWithDifferingPasswords on IE    TestFixtureSetUp failed in UserRegistrationFeature 5) Parent Failure : RegistrationForm.Tests.Acceptance.Features.UserRegistrationFeature.UserSignsUpWithDifferingPasswords on Chrome    TestFixtureSetUp failed in UserRegistrationFeature 6) Parent Failure : RegistrationForm.Tests.Acceptance.Features.UserRegistrationFeature.UserSignsUpWithValidDetails on Firefox    TestFixtureSetUp failed in UserRegistrationFeature 7) Parent Failure : RegistrationForm.Tests.Acceptance.Features.UserRegistrationFeature.UserSignsUpWithValidDetails on Safari    TestFixtureSetUp failed in UserRegistrationFeature 8) Parent Failure : RegistrationForm.Tests.Acceptance.Features.UserRegistrationFeature.UserSignsUpWithValidDetails on IE    TestFixtureSetUp failed in UserRegistrationFeature 9) Parent Failure : RegistrationForm.Tests.Acceptance.Features.UserRegistrationFeature.UserSignsUpWithValidDetails on Chrome    TestFixtureSetUp failed in UserRegistrationFeature  

Most of my atempts to fix this have been to edit the path to the dll in the transformed app.config file, though it should be the same as I am using nuget pachage restore.

**Comment by romerod** [comment]
Have you found a solution? 

Do you have direct access to the TFS server? Take a look at the log with Fuslogvw.exe

**Comment by radicalgeek** [comment]
Yes I did thank you, had to battle a few issues, but I got there in the end. I was using Visual Studio Online, so I couldn't just look on the server

Date: Fri, 10 Jan 2014 01:35:43 -0800
